### PR TITLE
Add serviceerror.NewerBuildExists

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**
- Bump api repo reference
- Add serviceerror.NewerBuildExists

**Why?**

**How did you test it?**

**Potential risks**

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
I wouldn’t even bother with this PR and just push to the feature branch directly

**Comment by dnr** [comment]
> I wouldn’t even bother with this PR and just push to the feature branch directly

sure, there is new hand-written code though

**Comment by bergundy** [comment]
Oh I didn’t realize we had any hand written code in this repo

**Comment by dnr** [comment]
serviceerrors are pretty boilerplate-y and would be nice to codegen, but they're still copy-paste for now

**Pull request merged**
