### PR TITLE
Update protos with account get/update operations

### PR DESCRIPTION
**Pull request by ennyjfrick**
**What changed?**
- Manually updated latest submodule for `proto/api-cloud`
- Ran `make` which updated the account update/get operations in addition to migration from string values to enums

**Why?**

**How did you test it?**

**Potential risks**

### CODE REVIEW

**Comment by bergundy** [comment]
Not super up-to-date with the status of Cloud protos. @anekkanti / @cretz, do you know if this is safe to upgrade? Is the change from string to enums implemented?

**Review by anekkanti — DISMISSED** [review]

**Review by bergundy — APPROVED** [review]

**Comment by ennyjfrick** [comment]
@bergundy thanks for the approval! Would you mind cutting a new release?

**Comment by bergundy** [comment]
Hey, I'm just verifying with our Cloud team that we're good to release and will get back to it.

**Comment by bergundy** [comment]
https://github.com/temporalio/api-go/releases/tag/v1.40.0

**Pull request merged**
